//
// Created by c1337 on 3/10/26.
//

#ifndef IMGUI_EXAMPLE_GLFW_VULKAN_SWAPCHAIN_H
#define IMGUI_EXAMPLE_GLFW_VULKAN_SWAPCHAIN_H


class SwapChain {
};


#endif //IMGUI_EXAMPLE_GLFW_VULKAN_SWAPCHAIN_H